listen_addresses = '*'
port = 5432
max_connections = 100
shared_buffers = 128MB
hba_file = '/etc/postgresql/pg_hba.conf'
ident_file = '/etc/postgresql/pg_ident.conf'
data_directory = '/var/lib/postgresql/data'